src/web/NSE.WebApp.MVC/Controllers/CartController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Models;
using NSE.WebApp.MVC.Services.Interfaces;

namespace NSE.WebApp.MVC.Controllers
{
    [Authorize]
    public class CartController : MainController
    {
        private readonly IPurchasesBffService _purchasesBffService;

        public CartController(IPurchasesBffService purchasesBffService)
        {
            _purchasesBffService = purchasesBffService;
        }

        [Route("cart")]
        public async Task<IActionResult> Index()
        {
            return View(await _purchasesBffService.GetCart());
        }

        [HttpPost]
        [Route("cart/add-item")]
        public async Task<IActionResult> AddNewItemCart(ItemCartViewModel itemCart)
        {
            var response = await _purchasesBffService.AddItemToCart(itemCart);
            if (ResponseAnyErrors(response)) return View("Index", await _purchasesBffService.GetCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("cart/update-item")]
        public async Task<IActionResult> UpdateCartItem(Guid productId, int quantity)
        {
            var itemProduct = new ItemCartViewModel() {ProductId = productId, Quantity = quantity};
            var response = await _purchasesBffService.UpdateItemFromCart(productId, itemProduct);

            if (ResponseAnyErrors(response)) return View("Index", await _purchasesBffService.GetCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("cart/remove-item")]
        public async Task<IActionResult> DeleteCartItem(Guid productId)
        {
            var response = await _purchasesBffService.RemoveItemFromCart(productId);
            if (ResponseAnyErrors(response)) return View("Index", await _purchasesBffService.GetCart());

            return RedirectToAction("Index");
        }
    }
}

src/web/NSE.WebApp.MVC/Controllers/CatalogController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Services.Interfaces;

namespace NSE.WebApp.MVC.Controllers
{
    public class CatalogController : MainController
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        [HttpGet]
        [Route("")]
        [Route("vitrine")]
        public async Task<IActionResult> Index()
        {
            var products = await _catalogService.FindAll();

            return View(products);
        }

        [HttpGet]
        [Route("product-details/{id}")]
        public async Task<IActionResult> ProductDetails(Guid id)
        {
            var product = await _catalogService.FindById(id);

            return View(product);
        }
    }
}

src/web/NSE.WebApp.MVC/Views/Catalog/Index.cshtml
@using NSE.WebApp.MVC.Extensions
@model IEnumerable<NSE.WebApp.MVC.Models.ProductViewModel>

@{
    ViewData["Title"] = "Todos os produtos";
}

<section>
    <div>
        <div style="background-image: url(images/banners/Template.jpg); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover">
            <div style="text-align: center;">
                <img src="~/images/banners/nerdstore.png" />
            </div>
        </div>
        <div class="container" style=" padding-top: 20px">
            <div class="row">
                @{
                    foreach (var products in Model.OrderBy(p => p.Name))
                    {
                        <div class="col-md-3">
                            <div href="#" class="card card-product-grid">
                                <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@products.Id" class="img-wrap">
                                    <img src="~/images/produtos/@products.Image" alt="@products.Name">
                                </a>
                                <figcaption class="info-wrap">
                                    <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@products.Id" class="title">
                                        <b> @products.Name</b>
                                    </a>

                                    <small class="card-text">
                                        @this.MessageInventory(products.InventoryQuantity)<br /><br />
                                        @products.Description
                                    </small>
                                </figcaption>
                                <div class="card-footer price mt-1">
                                    <h3>@this.CoinFormat(products.Value)</h3>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</section>

src/web/NSE.WebApp.MVC/Views/Catalog/ProductDetails.cshtml
@using NSE.WebApp.MVC.Extensions
@model NSE.WebApp.MVC.Models.ProductViewModel
@{
    ViewData["Title"] = Model.Name;
}
<section class="section-content padding-y bg container">
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap">
                    <div class="img-big-wrap" style="text-align: center">
                        <img src="~/images/produtos/@Model.Image" alt="@Model.Name">
                    </div>
                </article>
            </aside>
            <main class="col-md-6 border-left">
                <article class="content-body">
                    <form asp-controller="Cart" asp-action="AddNewItemCart" method="post">

                        <input type="hidden" id="ProductId" name="ProductId" value="@Model.Id" />

                        <h2 class="title">@Model.Name</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width: 80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 avaliações</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 peças vendidas</small>
                        </div>

                        <div class="mb-3">
                            <var class="price h4">@this.CoinFormat(Model.Value)</var>
                        </div>

                        <h5>@Model.Description</h5><br />
                        <p> @this.MessageInventory(Model.InventoryQuantity)</p>

                        <hr>

                        @{
                            if (Model.InventoryQuantity > 0)
                            {
                                <div class="form-row">
                                    <div class="form-group col-md flex-grow-0">
                                        <label>Quantidade</label>
                                        <div class="input-group input-spinner">
                                            <select class="form-control" id="Quantity" name="Quantity">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <br />
                                <button type="submit" class="btn  btn-outline-primary">
                                    <span class="text">Adicionar ao carrinho</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                                </button>
                            }
                        }

                        <a asp-action="Index" class="btn  btn-info">
                            <span class="text">Voltar</span>
                        </a>
                    </form>
                </article>
            </main>
        </div>
    </div>
</section>